equipos_index:
    path:     /
    defaults: { _controller: "AppBundle:Equipos:index" }
    methods:  GET

equipos_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Equipos:show" }
    methods:  GET



