jugadores_index:
    path:     /
    defaults: { _controller: "AppBundle:Jugadores:index" }
    methods:  GET

jugadores_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Jugadores:show" }
    methods:  GET



